### ISSUE TITLE
New repo checklist

### ISSUE THREAD

**Issue by justinchuby** [onnx/neural-compressor#1]
- [x] Must be owned and managed by one of the ONNX SIGs or the Steering Committee
- [x] Must be actively maintained
- [ ] Must adopt the ONNX Code of Conduct
- [ ] Must adopt the standard ONNX license(s) [All code projects use the Apache 2.0 license. 
- [ ] Documentation repositories must use the Creative Commons License version 4.0.]
- [ ] Must adopt the ONNX DCO bot
- [ ] Must adopt all ONNX automation (like static code analysis)
- [ ] Must have CI or other automation in place for repos containing code to ensure quality
- [ ] All OWNERS must be members of standing as defined by ability to vote in Steering Committee elections.
